-- SQL de criação do banco de dados para a ferramenta minhaFacul
-- Alexandre CASTILHO 21/04/2023
-- FACULDADE definition

CREATE TABLE FACULDADE (
	FACULDADE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FACULADE TEXT(300),
	LOCAL_GPC TEXT(8),
	CONSTRAINT FACULDADE_UN UNIQUE (FACULADE)
);


-- CURSO definition

CREATE TABLE CURSO (
	CURSO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CURSO TEXT(300),
	CONSTRAINT CURSO_UN UNIQUE (CURSO)
);


-- USUARIO definition

CREATE TABLE USUARIO (
	USUARIO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	EMAIL TEXT(300),
	SENHA_SHA256 TEXT(64),
	RECUPERA_SENHA INTEGER DEFAULT (0),
	ADMINISTRADOR INTEGER DEFAULT (0),
	CURSO_ID INTEGER,
	LOCAL_GPC TEXT(8),
	CONSTRAINT USUARIO_UN UNIQUE (EMAIL),
	CONSTRAINT USUARIO_FK FOREIGN KEY (CURSO_ID) REFERENCES CURSO(CURSO_ID)
);


-- HISTORICO definition

CREATE TABLE HISTORICO (
	HISTORICO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FACULDADE_ID INTEGER,
	CURSO_ID INTEGER,
	ANO INTEGER,
	VAGAS INTEGER,
	CANDIDATOS INTEGER,
	CONSTRAINT HISTORICO_UN UNIQUE (FACULDADE_ID,CURSO_ID,ANO),
	CONSTRAINT HISTORICO_FK FOREIGN KEY (FACULDADE_ID) REFERENCES FACULDADE(FACULDADE_ID),
	CONSTRAINT HISTORICO_FK_1 FOREIGN KEY (CURSO_ID) REFERENCES CURSO(CURSO_ID)
);

-- Cria um usuário administrador
INSERT INTO USUARIO
(EMAIL, SENHA_SHA256, RECUPERA_SENHA, ADMINISTRADOR, CURSO_ID, LOCAL_GPC)
VALUES('root@root.com', '4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2', 0, 1, 0, '');
